name: curl_logger_dio_interceptor
description: Get your http requests printed as curl command in your terminal. Share them easily with your colleagues and import them in Postman!
version: 2.0.0
homepage: https://github.com/OwnWeb/curl_logger_dio_interceptor

environment:
  sdk: ^3.0.1

dependencies:
  dio: ^5.1.2
  logger: ^2.0.1
  logging: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
